### PR TITLE
tracking 2023 updates

### LINKED ISSUE #12: update package to remove reliance deprecated `checkr` package
There is increased interest in re-vamping this package for use in calculating wqindex. The package currently relies upon deprecated `checkr`. I'm happy to modify package to incorporate `chk` functionality

### PR DESCRIPTION
**Pull request by KarHarker**
keeping track of 2023 updates here: 

- [x] update reliance of `checkr` to `chk`
- [x] update to `sf` package for plotting functions
- [x] update deprecated dplyr functions
- [ ] look at mapping functions

### CODE REVIEW

**Comment by KarHarker** [comment]
@joethorley - I've done the first round of updates to get the calc_wqi() function and related tests working. I would like to pull the work so far so people can use and see what they might be interested in for plotting and mapping options. I haven't updated the mapping/plotting functions yet, but did update deprecated ggplot2 functions. 

Feel free to review if interested

**Comment by joethorley** [comment]
Hi @KarHarker - Good work. Ideally each of the tick items would be its own PR to facilitate review and allow independent merging but what you have done works. I've made a PR request to have all current tests be run using GitHub actions on the various operating systems for any PR to the main/master branch see <https://github.com/bcgov/wqindex/pull/14>. Ideally this would be set up before we merge to double check all tests but at a first glance everything seems good to me. Well done.

**Comment by KarHarker** [comment]
Hi @joethorley, yes definitely will separate them into individual in future work. I wasn't totally sure what I was getting into there so it is a bit of a mix. 

Yes, it would be good to run the gh actions prior to merging -  I will wait until you merge the other PR. Thanks!

**Comment by joethorley** [comment]
@KarHarker - yes sometimes it just works out as mix. 

I don't have the authority to merge the PR so you'll need to do it.

**Comment by KarHarker** [comment]
Ok, I have done that now - thanks @joethorley!

**Pull request merged**
